name: EPUB [Uniffi] | Rust CI | Android

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wp-mini-epub-uniffi/src/**'
      - 'wp-mini-epub-uniffi/Cargo.toml'
      - 'wp-mini-epub-uniffi/.cargo/**'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - 'wp-mini-epub-uniffi/src/**'
      - 'wp-mini-epub-uniffi/Cargo.toml'
      - 'wp-mini-epub-uniffi/.cargo/**'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Install cargo-ndk
      uses: taiki-e/install-action@cargo-ndk

    - name: Install toolchains
      run: |
        rustup target add \
          aarch64-linux-android \
          armv7-linux-androideabi \
          x86_64-linux-android \
          i686-linux-android

    - name: Build
      working-directory: ./wp-mini-epub-uniffi 
      run: cargo ndk --platform 29 -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o ./jniLibs build --release
      
    - name: Generate Kotlin Bindings
      working-directory: ./wp-mini-epub-uniffi 
      run: cargo run --release --features=uniffi/cli --bin uniffi-bindgen generate --library jniLibs/arm64-v8a/libuniffi_wp_epub_mini.so --language kotlin --out-dir ./bindings/
      
    - name: Show all folders
      run: Get-ChildItem -Recurse
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: epub-uniffi-builds
        path: |
          ./wp-mini-epub-uniffi/jniLibs
          ./wp-mini-epub-uniffi/bindings
        if-no-files-found: error
